spring.application.name=Social-Bookmarking-Discovery-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/social_bookmarks
spring.datasource.username=dev
spring.datasource.password=dev
spring.security.user.name=dev
spring.security.user.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080
